import json

# 1. Define your mapping (fill in with your actual categories)
DOMAIN_TO_CATEGORY = {
   "Access & Equity": "Other",
"Access & Equity Considerations": "Other",
"Accessibility & Equity": "Other",
"Biological & Genomic Factors": "Biomarkers and personalized medicine",
"Biomarker & Genomic Considerations": "Biomarkers and personalized medicine",
"Biomarker & Personalization": "Biomarkers and personalized medicine",
"Biomarker & Personalized Medicine Considerations": "Biomarkers and personalized medicine",
"Biomarker & Personalized Medicine Factors": "Biomarkers and personalized medicine",
"Biomarker & Personalized Medicine Fit": "Biomarkers and personalized medicine",
"Biomarker & Personalized Medicine Value": "Biomarkers and personalized medicine",
"Biomarker & Precision Medicine Alignment": "Biomarkers and personalized medicine",
"Biomarker & Precision Medicine Considerations": "Biomarkers and personalized medicine",
"Biomarker & Precision Medicine Fit": "Biomarkers and personalized medicine",
"Biomarker & Precision Medicine Value": "Biomarkers and personalized medicine",
"Biomarker & Subgroup Benefits": "Biomarkers and personalized medicine",
"Biomarker & Subgroup Relevance": "Biomarkers and personalized medicine",
"Biomarker and Subgroup Benefits": "Biomarkers and personalized medicine",
"Clinical Effectiveness": "Clinical effectiveness",
"Clinical Efficacy": "Clinical effectiveness",
"Clinical Efficacy & Outcomes": "Clinical effectiveness",
"Clinical Efficacy & Safety": "Clinical effectiveness",
"Clinical Efficacy & Survival Outcomes": "Clinical effectiveness",
"Comparative & Alternative Options": "Other",
"Comparative & Alternative Therapies": "Other",
"Comparative & Contextual Factors": "Other",
"Comparative Effectiveness": "Clinical effectiveness",
"Comparative Effectiveness & Alternatives": "Other",
"Comparative Evidence": "Other",
"Comparative Value": "Other",
"Comparative Value (vs. Alternatives)": "Other",
"Comparative Value vs. Alternatives": "Other",
"Cost & Accessibility": "Cost",
"Cost & Economic Burden": "Cost",
"Cost & Economic Impact": "Cost",
"Cost & Financial Burden": "Cost",
"Cost & Financial Impact": "Cost",
"Cost and Accessibility": "Cost",
"Cost and Financial Impact": "Cost",
"Economic & Access Considerations": "Cost",
"Economic & Accessibility": "Cost",
"Economic & Accessibility Factors": "Cost",
"Economic & Financial Considerations": "Cost",
"Economic & Health System Impact": "Cost",
"Economic & Logistical Considerations": "Cost",
"Economic & Practical Considerations": "Cost",
"Economic Burden": "Cost",
"Emerging & Supportive Therapies": "Clinical effectiveness",
"Equity & Access": "Other",
"Equity & Access Considerations": "Other",
"Ethical & Access Considerations": "Patient-centered outcomes and preferences",
"Ethical & Equity Considerations": "Other",
"Ethical & Legal Considerations": "Other",
"Ethical & Psychosocial Support": "Patient-centered outcomes and preferences",
"Ethical & Shared Decision-Making Considerations": "Patient-centered outcomes and preferences",
"Ethical & Shared Decision-Making Factors": "Patient-centered outcomes and preferences",
"Ethical & Social Considerations": "Patient-centered outcomes and preferences",
"Ethical & Societal Considerations": "Other",
"Financial & Accessibility Considerations": "Cost",
"Financial & Economic Burden": "Cost",
"Financial & Economic Impact": "Cost",
"Financial & Practical Considerations": "Cost",
"Healthcare System & Access Factors": "Cost",
"Healthcare System & Logistical Factors": "Cost",
"Healthcare System & Policy Factors": "Cost",
"Healthcare System & Provider Factors": "Cost",
"Healthcare System & Societal Impact": "Other",
"Healthcare System & Support Services": "Cost",
"Healthcare System Factors": "Cost",
"Healthcare System Impact": "Other",
"Healthcare System and Logistical Factors": "Cost",
"Innovation & Future-Readiness": "Other",
"Long-Term & Survivorship Considerations": "Clinical effectiveness",
"Long-Term & Survivorship Impact": "Clinical effectiveness",
"Long-Term Health & Survivorship": "Clinical effectiveness",
"Long-Term Monitoring & Follow-Up": "Clinical effectiveness",
"Long-Term Monitoring & Survivorship": "Clinical effectiveness",
"Long-Term Monitoring & Survivorship Care": "Clinical effectiveness",
"Long-Term Outcomes": "Clinical effectiveness",
"Long-Term Outcomes & Survivorship": "Clinical effectiveness",
"Long-Term Survivorship & Follow-Up": "Clinical effectiveness",
"Long-Term Survivorship & Late Effects": "Clinical effectiveness",
"Novel/Experimental Therapies (if applicable)": "Other",
"Novelty & Evidence Strength": "Clinical effectiveness",
"Novelty & Future Potential": "Other",
"Novelty and Future Prospects": "Other",
"Patient Preferences & Goals": "Patient-centered outcomes and preferences",
"Patient Preferences & Shared Decision-Making": "Patient-centered outcomes and preferences",
"Patient Preferences & Values": "Patient-centered outcomes and preferences",
"Patient Preferences and Goals": "Patient-centered outcomes and preferences",
"Patient-Centered Factors": "Patient-centered outcomes and preferences",
"Patient-Centered Outcomes": "Patient-centered outcomes and preferences",
"Patient-Specific Factors": "Patient-centered outcomes and preferences",
"Personal & Cultural Preferences": "Patient-centered outcomes and preferences",
"Personalization & Biomarker Suitability": "Biomarkers and personalized medicine",
"Personalization & Biomarker-Driven Therapy": "Biomarkers and personalized medicine",
"Personalization & Biomarker-Driven Value": "Biomarkers and personalized medicine",
"Personalized & Genomic Factors": "Biomarkers and personalized medicine",
"Personalized & Precision Medicine Factors": "Biomarkers and personalized medicine",
"Personalized Medicine Factors": "Biomarkers and personalized medicine",
"Physician & Patient Trust in Evidence": "Other",
"Psychosocial & Supportive Care": "Patient-centered outcomes and preferences",
"Quality of Life (QoL) & Functional Impact": "Patient-centered outcomes and preferences",
"Quality of Life (QoL) & Functional Outcomes": "Patient-centered outcomes and preferences",
"Quality of Life (QoL) & Patient Experience": "Patient-centered outcomes and preferences",
"Quality of Life (QoL) & Patient-Reported Outcomes": "Patient-centered outcomes and preferences",
"Quality of Life (QoL) & Patient-Reported Outcomes (PROs)": "Patient-centered outcomes and preferences",
"Quality of Life (QoL) & Psychosocial Impact": "Patient-centered outcomes and preferences",
"Quality of Life (QoL) Impact": "Patient-centered outcomes and preferences",
"Quality of Life (QoL) and Patient-Reported Outcomes (PROs)": "Patient-centered outcomes and preferences",
"Real-World Evidence (RWE) & Clinical Trial Data": "Clinical effectiveness",
"Regulatory & Evidence-Based Support": "Clinical effectiveness",
"Safety & Side Effects": "Clinical effectiveness",
"Safety & Tolerability": "Clinical effectiveness",
"Safety and Tolerability": "Clinical effectiveness",
"Shared Decision-Making & Preferences": "Patient-centered outcomes and preferences",
"Social & Ethical Considerations": "Patient-centered outcomes and preferences",
"Social & Ethical Dimensions": "Patient-centered outcomes and preferences",
"Social & Support Considerations": "Patient-centered outcomes and preferences",
"Social & Support Factors": "Patient-centered outcomes and preferences",
"Social & Support Network Impact": "Patient-centered outcomes and preferences",
"Social & Support Systems": "Patient-centered outcomes and preferences",
"Support Systems & Integrative Care": "Cost",
"Supportive Care & Integrative Services": "Cost",
"Supportive Care & Multidisciplinary Needs": "Other",
"Supportive Care & Survivorship": "Clinical effectiveness",
"Survivorship & Long-Term Health": "Clinical effectiveness",
"Survivorship & Long-Term Outcomes": "Clinical effectiveness",
"Survivorship and Long-Term Outcomes": "Clinical effectiveness",
"Treatment Accessibility & Convenience": "Patient-centered outcomes and preferences",
"Treatment Accessibility & Equity": "Other",
"Treatment Accessibility & Logistics": "Other",
"Treatment Burden": "Patient-centered outcomes and preferences",
"Treatment Burden & Convenience": "Patient-centered outcomes and preferences",
"Treatment Burden and Convenience": "Patient-centered outcomes and preferences",
"Treatment Goals & Patient Preferences": "Patient-centered outcomes and preferences",
"Treatment Goals & Preferences": "Patient-centered outcomes and preferences",
"Treatment Modality & Accessibility": "Other",
"Treatment Modality & Convenience": "Patient-centered outcomes and preferences",
"Treatment Modality & Logistics": "Patient-centered outcomes and preferences",
"Treatment Modality & Logistics": "Patient-centered outcomes and preferences",
"Treatment Modality Considerations": "Other",
"Treatment Modality-Specific Metrics": "Other"
}

with open("extracted_domains_round2.json", "r", encoding="utf-8") as f:
    all_domains = json.load(f)

# 2. Append category for each domain
all_domains_with_categories = []
for response in all_domains:
    response_with_categories = []
    for domain in response:
        category = DOMAIN_TO_CATEGORY.get(domain, "Other")
        response_with_categories.append({"domain": domain, "category": category})
    all_domains_with_categories.append(response_with_categories)

# 3. Save the new structure
with open("domains_with_categories_round2.json", "w", encoding="utf-8") as f:
    json.dump(all_domains_with_categories, f, ensure_ascii=False, indent=2)

print("Saved domains with categories to domains_with_categories_round2.json")