import json

# 1. this mapping was done manually and validated by a domain expert
DOMAIN_TO_CATEGORY = {
    "Safety & Tolerability": "Clinical effectiveness",
    "Clinical Efficacy": "Clinical effectiveness",
    "Cost & Financial Impact": "Cost",
    "Quality of Life (QoL) & Patient-Reported Outcomes (PROs)": "Patient-centered outcomes and preferences",
    "Treatment Burden & Convenience": "Patient-centered outcomes and preferences",
    "Long-Term Outcomes & Survivorship": "Clinical effectiveness",
    "Biomarker & Personalized Medicine Considerations": "Biomarkers and personalized medicine",
    "Patient Preferences & Goals": "Patient-centered outcomes and preferences",
    "Comparative Effectiveness": "Clinical effectiveness",
    "Comparative Value vs. Alternatives": "Other",
    "Patient Preferences & Shared Decision-Making": "Patient-centered outcomes and preferences",
    "Patient Preferences & Values": "Patient-centered outcomes and preferences",
    "Clinical Efficacy & Outcomes": "Clinical effectiveness",
    "Safety & Side Effects": "Clinical effectiveness",
    "Long-Term Monitoring & Survivorship": "Clinical effectiveness",
    "Clinical Efficacy & Safety": "Clinical effectiveness",
    # Originally "Accessibilty & Equity"
    "Geographic and Social Barriers": "Other",
    "Treatment Accessibility & Logistics": "Other",
    "Comparative Value (vs. Alternatives)": "Other",
    "Treatment Modality & Convenience": "Patient-centered outcomes and preferences",
    "Biomarker & Personalized Medicine Fit": "Biomarkers and personalized medicine",
    "Comparative Value": "Other",
    "Social & Ethical Considerations": "Patient-centered outcomes and preferences",
    "Quality of Life (QoL) Impact": "Patient-centered outcomes and preferences",
    "Financial & Insurance Considerations": "Cost",
    "Long-Term & Survivorship Considerations": "Clinical effectiveness",
    "Biomarker & Precision Medicine Alignment": "Biomarkers and personalized medicine",
    "Treatment Modality & Accessibility": "Other",
    "Long-Term Outcomes": "Clinical effectiveness",
    "Quality of Life (QoL) & Psychosocial Impact": "Patient-centered outcomes and preferences",
    "Quality of Life (QoL)": "Patient-centered outcomes and preferences",
    "Quality of Life (QoL) & Patient-Reported Outcomes": "Patient-centered outcomes and preferences",
    "Biomarker & Personalized Medicine Value": "Biomarkers and personalized medicine",
    "Quality of Life (QoL) & Patient Experience": "Patient-centered outcomes and preferences",
    "Financial Considerations": "Cost",
    "Ethical & Societal Impact": "Other",
    "Cost & Financial Burden": "Cost",
    "Personalized Medicine Factors": "Biomarkers and personalized medicine",
    "Social & Support Factors": "Patient-centered outcomes and preferences",
    "Patient-Centered Factors": "Patient-centered outcomes and preferences",
    "Healthcare System & Logistical Factors": "Cost",
    "Long-Term & Survivorship Impact": "Clinical effectiveness",
    "Support Services & Resources": "Cost",
    "Comparative Alternatives": "Other",
    "Comparative & Alternative Options": "Other",
    # Originally "Access & Equity"
    "Geographic and Social Barriers": "Other",
    "Survivorship & Long-Term Outcomes": "Clinical effectiveness",
    "Treatment Goals & Preferences": "Patient-centered outcomes and preferences",
    "Personalized & Precision Medicine Factors": "Biomarkers and personalized medicine",
    "Cost & Accessibility": "Cost",
    "Social & Support Considerations": "Patient-centered outcomes and preferences",
    "Treatment Modality & Logistics": "Patient-centered outcomes and preferences",
    "Innovation & Future Potential": "Other",
    "Safety and Tolerability": "Clinical effectiveness",
    "Quality of Life (QoL) and Patient-Reported Outcomes (PROs)": "Patient-centered outcomes and preferences",
    "Social & Ethical Factors": "Patient-centered outcomes and preferences",
    "Research & Emerging Evidence": "Clinical effectiveness",
    "Ethical & Cultural Considerations": "Patient-centered outcomes and preferences",
    "Financial & Access Considerations": "Cost",
    "Personal Preferences & Values": "Patient-centered outcomes and preferences",
    "Ethical & Social Considerations": "Patient-centered outcomes and preferences",
    "Financial & Economic Burden": "Cost",
    "Comparative Effectiveness vs. Alternatives": "Other",
    "Comparative & Alternative Therapies": "Other",
    "Healthcare System & Support Services": "Cost",
    "Personalized Medicine & Biomarkers": "Biomarkers and personalized medicine",
    "Survivorship & Long-Term Monitoring": "Clinical effectiveness",
    "Treatment Burden": "Patient-centered outcomes and preferences",
    "Biomarker & Personalized Medicine Factors": "Biomarkers and personalized medicine",
    "Economic & Financial Impact": "Cost",
    "Regulatory & Evidence Strength": "Clinical effectiveness",
    "Ethical & Legal Considerations": "Other",
    "Personalization & Biomarker Suitability": "Biomarkers and personalized medicine",
    "Economic & Access Considerations": "Cost",
    "Treatment Modality & Burden": "Patient-centered outcomes and preferences",
    "Patient-Specific Factors": "Patient-centered outcomes and preferences",
    "Access & Logistical Feasibility": "Other",
    "Psychosocial & Emotional Impact": "Patient-centered outcomes and preferences",
    "Economic Considerations": "Cost",
    "Novelty & Evidence Strength": "Clinical effectiveness",
    "Long-Term Monitoring & Survivorship Care": "Clinical effectiveness",
    "Biomarker & Subgroup Benefits": "Biomarkers and personalized medicine",
    "Healthcare System & Societal Impact": "Other",
    "Treatment Burden and Convenience": "Patient-centered outcomes and preferences",
    "Cost and Financial Impact": "Cost",
    "Biomarker and Personalized Medicine Considerations": "Biomarkers and personalized medicine",
    "Patient Preferences and Values": "Patient-centered outcomes and preferences",
    "Long-Term Outcomes and Survivorship": "Clinical effectiveness",
    "Social and Ethical Considerations": "Patient-centered outcomes and preferences",
    "Financial & Economic Considerations": "Cost",
    "Patient-Centered & Psychosocial Factors": "Patient-centered outcomes and preferences",
    "Psychosocial & Supportive Care": "Patient-centered outcomes and preferences",
    "Long-term Monitoring & Follow-up": "Clinical effectiveness",
    "Research & Evidence Strength": "Clinical effectiveness",
    "Clinical Trial & Real-World Evidence": "Clinical effectiveness",
    "Personalized & Genomic Factors": "Biomarkers and personalized medicine",
    "Treatment Burden & Logistics": "Patient-centered outcomes and preferences",
    "Biomarker & Personalization": "Biomarkers and personalized medicine",
    "Survivorship & Long-Term Impact": "Clinical effectiveness",
    "Social & Caregiver Impact": "Patient-centered outcomes and preferences",
    "Alternative & Complementary Options": "Other",
    "Long-term Survivorship & Follow-up": "Clinical effectiveness",
    "Healthcare System & Access": "Cost",
    "Treatment Setting & Alternatives": "Other",
    "Long-Term Monitoring & Follow-Up": "Clinical effectiveness",
    "Cost and Accessibility": "Cost",
    "Biomarker and Subgroup Benefits": "Biomarkers and personalized medicine",
    "Patient Preferences and Goals": "Patient-centered outcomes and preferences",
    "Social and Support Factors": "Patient-centered outcomes and preferences",
    "Cost & Economic Impact": "Cost",
    "Ethical & Psychosocial Considerations": "Patient-centered outcomes and preferences",
    "Social & Support System Impact": "Patient-centered outcomes and preferences",
    "Financial & Logistical Considerations": "Cost",
    "Personalization & Biomarker-Driven Value": "Biomarkers and personalized medicine",
    "Biomarker & Subgroup Relevance": "Biomarkers and personalized medicine",
    "Survivorship & Long-Term Care": "Clinical effectiveness",
    "Emerging Evidence & Future Prospects": "Clinical effectiveness",
    "Long-Term Survivorship & Follow-Up": "Clinical effectiveness",
    "Treatment Modality & Invasiveness": "Patient-centered outcomes and preferences",
    "Social & Support Systems": "Patient-centered outcomes and preferences",
    "Supportive Care & Integrative Services": "Cost",
    # Originally "Ethical & Access Equity Factors"
    "Geographic and Social Barriers": "Other",
    "Emerging Evidence & Research": "Clinical effectiveness",
    "Long-Term Health & Survivorship": "Clinical effectiveness",
    "Provider & Facility Factors": "Cost",
    "Patient-Reported Outcomes (PROs) & Satisfaction": "Patient-centered outcomes and preferences",
    "Evidence Strength & Guidelines": "Clinical effectiveness",
    "Evidence & Research Data": "Clinical effectiveness",
    "Regulatory & Ethical Considerations": "Other",
    "Economic & Financial Burden": "Cost",
    "Biomarker & Precision Medicine Considerations": "Biomarkers and personalized medicine",
    "Treatment Sequencing & Comparative Effectiveness": "Other",
    "Long-Term Survivorship & Follow-Up Care": "Clinical effectiveness",
    "Equity & Disparities": "Cost",
    "Patient-Centered Outcomes": "Patient-centered outcomes and preferences",
    "Treatment Modality & Practicality": "Patient-centered outcomes and preferences",
    "Long-Term Survivorship & Late Effects": "Clinical effectiveness",
    "Ethical & Psychosocial Impact": "Patient-centered outcomes and preferences",
    "Healthcare System & Policy Factors": "Cost",
    "Healthcare System & Provider Factors": "Cost",
    "Regulatory & Evidence-Based Support": "Clinical effectiveness",
    "Treatment Logistics & Accessibility": "Other",
    "Supportive Care & Resources": "Cost",
    "Ethical & Access Considerations": "Other",
    "Treatment Setting & Accessibility": "Other",
}

with open("extracted_domains.json", "r", encoding="utf-8") as f:
    all_domains = json.load(f)

# 2. Append category for each domain
all_domains_with_categories = []
for response in all_domains:
    response_with_categories = []
    for domain in response:
        category = DOMAIN_TO_CATEGORY.get(domain, "Other")
        response_with_categories.append({"domain": domain, "category": category})
    all_domains_with_categories.append(response_with_categories)

# 3. Save the new structure
with open("domains_with_categories.json", "w", encoding="utf-8") as f:
    json.dump(all_domains_with_categories, f, ensure_ascii=False, indent=2)

print("Saved domains with categories to domains_with_categories.json")